Cargo.toml
src/agent.rs

This function accepts anything that can be converted into
`service_binding::Listener` and that includes standard library's
`UnixListener` and `TcpListener`. This makes the `listen` method one
universal function that should be preferred.
Since `listen` does not expose any Tokio 0.x types and `service_binding`
has no dependencies this feature has minimal weight.

Add universal `listen` function

---

src/proto/extension.rs
src/proto/message.rs
src/proto/mod.rs
src/proto/ser.rs
src/proto/tests/mod.rs

This rollback #8, which turned out to be incorrect.
The `ExtensionContent` object isn't really standard and pretty unexpected.
This also includes a sample implementation of a `struct SessionBind` that will serialize and deserialize correctly.

Fixup extension serialization

---

README.md
examples/key_storage.rs
src/agent.rs

Splits Agent activities (listening and creating sessions) and Session activities (handling messages) into two separate traits allowing per-session state to be stored.
New code should implement `Session` and either `Default` (if no session state is required) or `Agent::new_session` if a specialized Session object is required.
This provides minimal changes to existing clients but also allows more flexible behavior.

Split Agent and Session for per-session use-cases

---

README.md
examples/key_storage.rs
src/agent.rs
src/error.rs

This allows clients to directly use `?` with their error types instead of mapping everything to `AgentError` which obscures the error reason.

Relax the error type in handle

---

.github/workflows/ci.yml
examples/key_storage.rs
tests/sign-and-verify-win.bat
tests/sign-and-verify.sh

This PR addresses the problem of checking if the agent is properly functioning for it's most basic task: signing requests.
Instead of spawning a new sshd daemon this PR takes a different approach: using SSH file signatures which execute the same piece of code.
On Windows a slight change is required: a file is created to signal to the script that it's ready to serve requests. Sadly it doesn't seem that checking `IF EXISTS "\\.\pipe\agent"` works :/

Add integration tests

---

Cargo.toml

Return-position `impl Trait` in traits requires Rust 1.75.
- https://github.com/wiktor-k/ssh-agent-lib/blob/3263c3d04900078c287880e76177ebd717c5540f/src/agent.rs#L145
- https://blog.rust-lang.org/2023/12/28/Rust-1.75.0.html

Document MSRV in Cargo.toml

---

.github/workflows/ci.yml

When the integration test fails to build on Windows the job is stuck waiting for the socket. Make it fail after 10 minutes which should be enough for the successful run.

Add timeout to integration tests

---

src/lib.rs

Using unsafe blocks makes the fuzzer use more resources.
See: https://github.com/wiktor-k/ssh-agent-lib/pull/38

Disallow using unsafe code

---

Cargo.lock
Cargo.toml
fuzz/.gitignore
fuzz/Cargo.toml
fuzz/README.md
fuzz/fuzz_targets/message_decode.rs

See `fuzz/README.md` for details on how to run it.

Add fuzzing setup for `Message::decode`

---

Cargo.toml
README.md
examples/key_storage.rs
fuzz/Cargo.toml
fuzz/fuzz_targets/request_decode.rs
src/agent.rs
src/codec.rs
src/lib.rs
src/proto/message.rs
tests/roundtrip.rs
tests/sign-and-verify.sh

As it says on the tin.
It makes the type system check if we're not sending requests as replies in the agent and vice versa.
I think some cleanup is still needed (e.g. not using `message` as a variable name, or duplication in `Request::SignRequest`) but I'm filing it earlier to gather your feedback :)

Split `Message` into `Request` and `Response`

---

src/proto.rs

After the rustcrypto refactor, this type alias was left over

unused type alias

---

src/proto/extension.rs

This also splits the `DestinationConstraints` implementation in a subtype for ease and readability.

extension: impl `Encode` for known extensions

---

README.md
examples/key_storage.rs
src/agent.rs
src/error.rs

This should alleviate issues with Extension Failed / Failed errors.
I get the feeling that a couple of swings more and we'll have a "final" design ready :)

Migrate back to using `AgentError` in `Session` methods

---

src/agent.rs
src/codec.rs
src/error.rs
src/proto.rs
src/proto/error.rs
src/proto/extension.rs
src/proto/message.rs
src/proto/privatekey.rs
src/proto/signature.rs

This PR adds documentation for the structures in the `proto` module with references back to the agent protocol specification.
I'll come back later and add top-level documentation for these modules.
I've held off on documenting the `agent` module as it's undergoing a bit of renovation at the moment!
I've tried to say as close to the specification with this documentation, but have added some simplifications of the spec in some places, so very open to feedback / nits :^)

Document vast majority of protocol messages

---

Cargo.lock
Cargo.toml
examples/ssh-agent-client.rs
src/agent.rs
src/client.rs
src/lib.rs
src/proto/error.rs

<del>I'm not happy with the API (especially the Client requiring type for the `ListeningSocket`)</del> but overall this works so I'm sharing for any potential feedback :)

Add SSH agent client with an example

---

examples/key_storage.rs
src/proto/message.rs

Because payload has already been read from the wire and copied in the `Unparsed` structure, the extension doesn't need to be mutable to be deserialized.

`Extension::parse` doesn't require mutability

---

examples/key_storage.rs
src/proto/message.rs

Following on from #58, I noticed that key constraint extensions don't need `&mut self` in method calls either.
Thanks for the pickup @baloo!

Remove unused `&mut self` in key constraint extension parsing

---

.env
.github/workflows/misc.yml
.github/workflows/rust.yml
.justfile
Cargo.lock
Cargo.toml
examples/openpgp-card-agent.rs

I've added a more elaborate example of an SSH agent. Actually this is a code that I'm planning to use (semi-)daily.
It has a couple of limitations, first of all it supports ed25519 keys only but I think it's a good idea to show how agents can be built and also serves as a validation of our API.

Add OpenPGP Card example

---

Cargo.lock
Cargo.toml
examples/pgp-wrapper.rs

Creates an OpenPGP certificate based on the SSH key and allows signing files emitting OpenPGP framed packets.
Requires that the first key in SSH is ed25519 (see `ssh-add -L`).
Generate a key with:
`cargo run --example pgp-wrapper generate "John Doe <john@example.com>" > key.pgp`
Sign data using:
`cargo run --example pgp-wrapper sign < Cargo.toml > Cargo.toml.sig`
Import the certificate using GnuPG:
```sh
$ gpg --import key.pgp
gpg: key A142E92C91BE3AD5: public key "John Doe <john@example.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
```
Verify the signature using GnuPG:
```sh
$ gpg --verify Cargo.toml.sig
gpg: assuming signed data in 'Cargo.toml'
gpg: Signature made Fri May 10 11:15:53 2024 CEST
gpg:                using EDDSA key …
```

Add `pgp-wrapper` example

---

src/proto/message/unparsed.rs

Add conversion methods to gain access to the inner bytes of `Unparsed`,
per discussion in https://github.com/wiktor-k/ssh-agent-lib/pull/72
Signed-off-by: Ross Williams <ross@ross-williams.net>

Implement `AsRef<[u8]>` and `into_bytes(self)` for `Unparsed`

---

Cargo.toml
examples/extensions.rs
examples/openpgp-card-agent.rs
examples/pgp-wrapper.rs
examples/ssh-agent-client.rs

Adds the `decrypt-derive-ids@metacode.biz` and `decrypt-derive@metacode.biz` extensions with encoding and decoding rules.
The extension is used to facilitate curve 25519 decryption over SSH agent connections.
This PR additionally makes the OpenPGP Card agent example implement these two extensions thus providing clients with public keys of its decryption keys. Additionally a `decrypt derive` extension similar to the sign request is implemented.
The PGP wrapper example has been extended to emit encryption subkeys if the agent supports them. An extra `decrypt` subcommand has been added. The docs have been updated to showcase how to use the feature:
```sh
echo I like strawberries | gpg -er 4EB27E153DDC454364B36B59A142E92C91BE3AD5 > /tmp/encrypted.pgp
SSH_AUTH_SOCK=/tmp/ext-agent.sock cargo …
```

Add an example of using SSH agent extensions for curve 25519 decryption

---

Cargo.lock
Cargo.toml

This is just a maintenance PR since cargo deny is getting upset because of the issue in curve25519-dalek (which seems to be a transitive dependency of ssh-key).

Update dependencies resolving `curve25519-dalek` issue

---

Cargo.lock

This fixes warnings emitted by CI because bytes was yanked (https://crates.io/crates/bytes/1.6.0)

chore: bump bytes, remove usage of a yanked crate

---

Cargo.lock
Cargo.toml

Hello!
Over at 1Password, we're looking into replacing `ssh-agent.rs` with this library. However, we're mainly just using the `proto` and `codec` modules (e.g. we use `default-features = false, features = ["codec"]`). It looks like the `service-binding` dependency is only used in the `agent` feature, and since we aren't using it, we'd like to avoid pulling it into our dependency tree.
This PR makes `service-binding` optional and pulls it in via the `agent` feature.

Put `service-binding` dependency under `agent` feature
